### ISSUE TITLE
URDF Reader error even after building with RBDL_BUILD_ADDON_URDFREADER=ON 

### ISSUE THREAD

**Issue by Prathamesh-Saraf** [ORB-HD/rbdl-orb#70]
![image](https://user-images.githubusercontent.com/76988781/126479410-ad6f6394-c7cf-4e33-9be0-9aba491b68e6.png)

The required files are generated after building with RBDL_BUILD_ADDON_URDFREADER=ON  but I still get this error when I run the example

**Comment by ju6ge** [comment]
You probably need to use the `-I` option to specify the include directory ;)

I strongly recommend using Cmake, then things like this become a lot easier. With the merge of the Casadi PR we will also add FindRBDl.cmake files, so that all you need to do is use find_package(RBDL COMPONENTS URDFREADER) within your CMakeLists.txt.

**Comment by Prathamesh-Saraf** [comment]
Thanks for your reply! I tried using -I but no success. Also, I have CMake 3.18.4 version installed. I'm still getting the same error

**Comment by ju6ge** [comment]
I suggest you read up on how to use cmake.

All the examples come with their own CMakeLists.txt files so all you need to do is create a build directory. Within the build directory run `cmake` and point it to the CMakeLists.txt file of the example. And afterwards run `make`.
